// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts/accounts.proto

package accounts

import (
	context "context"
	fmt "fmt"
	characters "github.com/MruV-RP/mruv-pb-go/characters"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountID struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountID) Reset()         { *m = AccountID{} }
func (m *AccountID) String() string { return proto.CompactTextString(m) }
func (*AccountID) ProtoMessage()    {}
func (*AccountID) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{0}
}

func (m *AccountID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountID.Unmarshal(m, b)
}
func (m *AccountID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountID.Marshal(b, m, deterministic)
}
func (m *AccountID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountID.Merge(m, src)
}
func (m *AccountID) XXX_Size() int {
	return xxx_messageInfo_AccountID.Size(m)
}
func (m *AccountID) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountID.DiscardUnknown(m)
}

var xxx_messageInfo_AccountID proto.InternalMessageInfo

func (m *AccountID) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Account struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login                string   `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Nick                 string   `protobuf:"bytes,3,opt,name=nick,proto3" json:"nick,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{1}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Account) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Account) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterAccountRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAccountRequest) Reset()         { *m = RegisterAccountRequest{} }
func (m *RegisterAccountRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterAccountRequest) ProtoMessage()    {}
func (*RegisterAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{2}
}

func (m *RegisterAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAccountRequest.Unmarshal(m, b)
}
func (m *RegisterAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAccountRequest.Marshal(b, m, deterministic)
}
func (m *RegisterAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAccountRequest.Merge(m, src)
}
func (m *RegisterAccountRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterAccountRequest.Size(m)
}
func (m *RegisterAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAccountRequest proto.InternalMessageInfo

func (m *RegisterAccountRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *RegisterAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterAccountResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccountId            uint32   `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAccountResponse) Reset()         { *m = RegisterAccountResponse{} }
func (m *RegisterAccountResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterAccountResponse) ProtoMessage()    {}
func (*RegisterAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{3}
}

func (m *RegisterAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAccountResponse.Unmarshal(m, b)
}
func (m *RegisterAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAccountResponse.Marshal(b, m, deterministic)
}
func (m *RegisterAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAccountResponse.Merge(m, src)
}
func (m *RegisterAccountResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterAccountResponse.Size(m)
}
func (m *RegisterAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAccountResponse proto.InternalMessageInfo

func (m *RegisterAccountResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterAccountResponse) GetAccountId() uint32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type LogInRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogInRequest) Reset()         { *m = LogInRequest{} }
func (m *LogInRequest) String() string { return proto.CompactTextString(m) }
func (*LogInRequest) ProtoMessage()    {}
func (*LogInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{4}
}

func (m *LogInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogInRequest.Unmarshal(m, b)
}
func (m *LogInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogInRequest.Marshal(b, m, deterministic)
}
func (m *LogInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogInRequest.Merge(m, src)
}
func (m *LogInRequest) XXX_Size() int {
	return xxx_messageInfo_LogInRequest.Size(m)
}
func (m *LogInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogInRequest proto.InternalMessageInfo

func (m *LogInRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *LogInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LogInResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccountId            uint32   `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogInResponse) Reset()         { *m = LogInResponse{} }
func (m *LogInResponse) String() string { return proto.CompactTextString(m) }
func (*LogInResponse) ProtoMessage()    {}
func (*LogInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{5}
}

func (m *LogInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogInResponse.Unmarshal(m, b)
}
func (m *LogInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogInResponse.Marshal(b, m, deterministic)
}
func (m *LogInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogInResponse.Merge(m, src)
}
func (m *LogInResponse) XXX_Size() int {
	return xxx_messageInfo_LogInResponse.Size(m)
}
func (m *LogInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogInResponse proto.InternalMessageInfo

func (m *LogInResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LogInResponse) GetAccountId() uint32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type GetAccountCharactersResponse struct {
	Characters           []*characters.Character `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetAccountCharactersResponse) Reset()         { *m = GetAccountCharactersResponse{} }
func (m *GetAccountCharactersResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountCharactersResponse) ProtoMessage()    {}
func (*GetAccountCharactersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{6}
}

func (m *GetAccountCharactersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountCharactersResponse.Unmarshal(m, b)
}
func (m *GetAccountCharactersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountCharactersResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountCharactersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountCharactersResponse.Merge(m, src)
}
func (m *GetAccountCharactersResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountCharactersResponse.Size(m)
}
func (m *GetAccountCharactersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountCharactersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountCharactersResponse proto.InternalMessageInfo

func (m *GetAccountCharactersResponse) GetCharacters() []*characters.Character {
	if m != nil {
		return m.Characters
	}
	return nil
}

// Request message for rpc `IsAccountExists`.
type IsAccountExistsRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAccountExistsRequest) Reset()         { *m = IsAccountExistsRequest{} }
func (m *IsAccountExistsRequest) String() string { return proto.CompactTextString(m) }
func (*IsAccountExistsRequest) ProtoMessage()    {}
func (*IsAccountExistsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{7}
}

func (m *IsAccountExistsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAccountExistsRequest.Unmarshal(m, b)
}
func (m *IsAccountExistsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAccountExistsRequest.Marshal(b, m, deterministic)
}
func (m *IsAccountExistsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAccountExistsRequest.Merge(m, src)
}
func (m *IsAccountExistsRequest) XXX_Size() int {
	return xxx_messageInfo_IsAccountExistsRequest.Size(m)
}
func (m *IsAccountExistsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAccountExistsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsAccountExistsRequest proto.InternalMessageInfo

func (m *IsAccountExistsRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

// Response message for rpc `IsAccountExists`.
type IsAccountExistsResponse struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Id                   uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAccountExistsResponse) Reset()         { *m = IsAccountExistsResponse{} }
func (m *IsAccountExistsResponse) String() string { return proto.CompactTextString(m) }
func (*IsAccountExistsResponse) ProtoMessage()    {}
func (*IsAccountExistsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da251b36fd5e693, []int{8}
}

func (m *IsAccountExistsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAccountExistsResponse.Unmarshal(m, b)
}
func (m *IsAccountExistsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAccountExistsResponse.Marshal(b, m, deterministic)
}
func (m *IsAccountExistsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAccountExistsResponse.Merge(m, src)
}
func (m *IsAccountExistsResponse) XXX_Size() int {
	return xxx_messageInfo_IsAccountExistsResponse.Size(m)
}
func (m *IsAccountExistsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAccountExistsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsAccountExistsResponse proto.InternalMessageInfo

func (m *IsAccountExistsResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *IsAccountExistsResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*AccountID)(nil), "mruv.AccountID")
	proto.RegisterType((*Account)(nil), "mruv.Account")
	proto.RegisterType((*RegisterAccountRequest)(nil), "mruv.RegisterAccountRequest")
	proto.RegisterType((*RegisterAccountResponse)(nil), "mruv.RegisterAccountResponse")
	proto.RegisterType((*LogInRequest)(nil), "mruv.LogInRequest")
	proto.RegisterType((*LogInResponse)(nil), "mruv.LogInResponse")
	proto.RegisterType((*GetAccountCharactersResponse)(nil), "mruv.GetAccountCharactersResponse")
	proto.RegisterType((*IsAccountExistsRequest)(nil), "mruv.IsAccountExistsRequest")
	proto.RegisterType((*IsAccountExistsResponse)(nil), "mruv.IsAccountExistsResponse")
}

func init() { proto.RegisterFile("accounts/accounts.proto", fileDescriptor_5da251b36fd5e693) }

var fileDescriptor_5da251b36fd5e693 = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x9d, 0xb4, 0x69, 0xa6, 0x84, 0x48, 0xdb, 0x2a, 0xb1, 0xdc, 0x54, 0x04, 0x1f, 0x68,
	0x0e, 0xc4, 0x0b, 0xe1, 0x05, 0x28, 0x14, 0x81, 0xc5, 0xaf, 0x8c, 0x84, 0x04, 0x12, 0x42, 0x8e,
	0xbd, 0x72, 0x57, 0x24, 0x5e, 0xe3, 0x5d, 0xa7, 0x48, 0x88, 0x0b, 0x57, 0x8e, 0x3c, 0x1a, 0xaf,
	0xc0, 0x83, 0xa0, 0x78, 0xc7, 0xce, 0x6f, 0x73, 0xe9, 0x6d, 0x67, 0xe6, 0xdb, 0x6f, 0xbf, 0xf9,
	0x66, 0x6c, 0xe8, 0x06, 0x61, 0x28, 0xf2, 0x44, 0x49, 0x5a, 0x1e, 0xdc, 0x34, 0x13, 0x4a, 0x90,
	0xfa, 0x34, 0xcb, 0x67, 0x76, 0x2f, 0x16, 0x22, 0x9e, 0x30, 0x1a, 0xa4, 0x9c, 0x06, 0x49, 0x22,
	0x54, 0xa0, 0xb8, 0x48, 0x10, 0x63, 0x9f, 0x84, 0x97, 0x41, 0x16, 0x84, 0x8a, 0x65, 0x92, 0x2e,
	0x8e, 0xba, 0xe8, 0x9c, 0x40, 0xf3, 0x5c, 0x53, 0x7a, 0x17, 0xe4, 0x36, 0x98, 0x3c, 0xb2, 0x8c,
	0xbe, 0x31, 0x68, 0xf9, 0x26, 0x8f, 0x9c, 0x8f, 0xd0, 0xc0, 0xe2, 0x7a, 0x89, 0x1c, 0xc3, 0xde,
	0x44, 0xc4, 0x3c, 0xb1, 0xcc, 0xbe, 0x31, 0x68, 0xfa, 0x3a, 0x20, 0x04, 0xea, 0x09, 0x0f, 0xbf,
	0x5a, 0xb5, 0x22, 0x59, 0x9c, 0xe7, 0x48, 0x36, 0x0d, 0xf8, 0xc4, 0xaa, 0x6b, 0x64, 0x11, 0x38,
	0x9f, 0xa1, 0xe3, 0xb3, 0x98, 0x4b, 0xc5, 0x32, 0x7c, 0xc2, 0x67, 0xdf, 0x72, 0x26, 0x15, 0x39,
	0x83, 0x06, 0x36, 0x59, 0x3c, 0x77, 0x38, 0x6a, 0xb9, 0xf3, 0x26, 0xdd, 0x12, 0x56, 0x56, 0x89,
	0x0d, 0x07, 0x69, 0x20, 0xe5, 0x95, 0xc8, 0x22, 0x54, 0x51, 0xc5, 0x8e, 0x0f, 0xdd, 0x0d, 0x7a,
	0x99, 0x8a, 0x44, 0x32, 0x62, 0x41, 0x43, 0xe6, 0x61, 0xc8, 0xa4, 0x2c, 0xf8, 0x0f, 0xfc, 0x32,
	0x24, 0xa7, 0x00, 0xc8, 0xfd, 0x85, 0x6b, 0xca, 0x96, 0xdf, 0xc4, 0x8c, 0x17, 0x39, 0x8f, 0xe1,
	0xd6, 0x2b, 0x11, 0x7b, 0x49, 0x29, 0xb4, 0xb2, 0xc0, 0x58, 0xb6, 0x60, 0x97, 0xaa, 0x17, 0xd0,
	0x42, 0x86, 0x9b, 0x6a, 0x79, 0x0b, 0xbd, 0xe7, 0x4c, 0x61, 0x6b, 0x4f, 0xab, 0xa1, 0x56, 0xc4,
	0x14, 0x60, 0x31, 0x6a, 0xcb, 0xe8, 0xd7, 0x06, 0x87, 0xa3, 0xb6, 0xf6, 0xb1, 0x42, 0xfb, 0x4b,
	0x10, 0xc7, 0x85, 0x8e, 0x27, 0x91, 0xef, 0xd9, 0x77, 0x2e, 0x95, 0xdc, 0xd9, 0xa6, 0x73, 0x0e,
	0xdd, 0x0d, 0x3c, 0xbe, 0xdd, 0x81, 0x7d, 0x56, 0x64, 0xb0, 0x27, 0x8c, 0x70, 0x85, 0xcc, 0x72,
	0x85, 0x46, 0xbf, 0x6b, 0x70, 0xf4, 0x3a, 0xcb, 0x3f, 0x20, 0x8b, 0x7c, 0xcf, 0xb2, 0x19, 0x0f,
	0x19, 0x79, 0x03, 0xed, 0xb5, 0xd9, 0x91, 0x9e, 0x96, 0xbe, 0x7d, 0x63, 0xec, 0xd3, 0x6b, 0xaa,
	0xa8, 0xe7, 0x01, 0xec, 0x15, 0xae, 0x13, 0xa2, 0x71, 0xcb, 0x43, 0xb4, 0x8f, 0x56, 0x72, 0x78,
	0xe3, 0x0a, 0xda, 0x6b, 0xcd, 0x95, 0x0a, 0xb6, 0x7b, 0x54, 0x2a, 0xb8, 0xc6, 0x11, 0xe7, 0xec,
	0xd7, 0xdf, 0x7f, 0x7f, 0xcc, 0xbb, 0xe4, 0x0e, 0x9d, 0x3d, 0xac, 0xbe, 0x60, 0xfa, 0xa3, 0x70,
	0xf2, 0x27, 0xcd, 0x50, 0x37, 0x8b, 0xc8, 0x7d, 0x80, 0xc5, 0x58, 0x49, 0x7b, 0x65, 0xf1, 0xbd,
	0x0b, 0x7b, 0xf5, 0x4b, 0x20, 0x2f, 0xe1, 0x78, 0xdb, 0x12, 0x6c, 0xde, 0x73, 0x74, 0x62, 0xd7,
	0xc6, 0x3c, 0x19, 0x7c, 0xba, 0x17, 0x73, 0x75, 0x99, 0x8f, 0xdd, 0x50, 0x4c, 0xe9, 0x7c, 0x2e,
	0x43, 0xff, 0x1d, 0x9d, 0xdf, 0x1b, 0xa6, 0xe3, 0x61, 0x2c, 0x2a, 0xdd, 0xe3, 0xfd, 0xe2, 0xcf,
	0xf1, 0xe8, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xc3, 0x29, 0xe0, 0x95, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MruVAccountsServiceClient is the client API for MruVAccountsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MruVAccountsServiceClient interface {
	RegisterAccount(ctx context.Context, in *RegisterAccountRequest, opts ...grpc.CallOption) (*RegisterAccountResponse, error)
	LogIn(ctx context.Context, in *LogInRequest, opts ...grpc.CallOption) (*LogInResponse, error)
	// Check, is account with specified login exists. If yes, it returns account id.
	IsAccountExists(ctx context.Context, in *IsAccountExistsRequest, opts ...grpc.CallOption) (*IsAccountExistsResponse, error)
	GetAccount(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*Account, error)
	GetAccountCharacters(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*GetAccountCharactersResponse, error)
}

type mruVAccountsServiceClient struct {
	cc *grpc.ClientConn
}

func NewMruVAccountsServiceClient(cc *grpc.ClientConn) MruVAccountsServiceClient {
	return &mruVAccountsServiceClient{cc}
}

func (c *mruVAccountsServiceClient) RegisterAccount(ctx context.Context, in *RegisterAccountRequest, opts ...grpc.CallOption) (*RegisterAccountResponse, error) {
	out := new(RegisterAccountResponse)
	err := c.cc.Invoke(ctx, "/mruv.MruVAccountsService/RegisterAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mruVAccountsServiceClient) LogIn(ctx context.Context, in *LogInRequest, opts ...grpc.CallOption) (*LogInResponse, error) {
	out := new(LogInResponse)
	err := c.cc.Invoke(ctx, "/mruv.MruVAccountsService/LogIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mruVAccountsServiceClient) IsAccountExists(ctx context.Context, in *IsAccountExistsRequest, opts ...grpc.CallOption) (*IsAccountExistsResponse, error) {
	out := new(IsAccountExistsResponse)
	err := c.cc.Invoke(ctx, "/mruv.MruVAccountsService/IsAccountExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mruVAccountsServiceClient) GetAccount(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/mruv.MruVAccountsService/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mruVAccountsServiceClient) GetAccountCharacters(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*GetAccountCharactersResponse, error) {
	out := new(GetAccountCharactersResponse)
	err := c.cc.Invoke(ctx, "/mruv.MruVAccountsService/GetAccountCharacters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MruVAccountsServiceServer is the server API for MruVAccountsService service.
type MruVAccountsServiceServer interface {
	RegisterAccount(context.Context, *RegisterAccountRequest) (*RegisterAccountResponse, error)
	LogIn(context.Context, *LogInRequest) (*LogInResponse, error)
	// Check, is account with specified login exists. If yes, it returns account id.
	IsAccountExists(context.Context, *IsAccountExistsRequest) (*IsAccountExistsResponse, error)
	GetAccount(context.Context, *AccountID) (*Account, error)
	GetAccountCharacters(context.Context, *AccountID) (*GetAccountCharactersResponse, error)
}

// UnimplementedMruVAccountsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMruVAccountsServiceServer struct {
}

func (*UnimplementedMruVAccountsServiceServer) RegisterAccount(ctx context.Context, req *RegisterAccountRequest) (*RegisterAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAccount not implemented")
}
func (*UnimplementedMruVAccountsServiceServer) LogIn(ctx context.Context, req *LogInRequest) (*LogInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogIn not implemented")
}
func (*UnimplementedMruVAccountsServiceServer) IsAccountExists(ctx context.Context, req *IsAccountExistsRequest) (*IsAccountExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAccountExists not implemented")
}
func (*UnimplementedMruVAccountsServiceServer) GetAccount(ctx context.Context, req *AccountID) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (*UnimplementedMruVAccountsServiceServer) GetAccountCharacters(ctx context.Context, req *AccountID) (*GetAccountCharactersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountCharacters not implemented")
}

func RegisterMruVAccountsServiceServer(s *grpc.Server, srv MruVAccountsServiceServer) {
	s.RegisterService(&_MruVAccountsService_serviceDesc, srv)
}

func _MruVAccountsService_RegisterAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MruVAccountsServiceServer).RegisterAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mruv.MruVAccountsService/RegisterAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MruVAccountsServiceServer).RegisterAccount(ctx, req.(*RegisterAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MruVAccountsService_LogIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MruVAccountsServiceServer).LogIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mruv.MruVAccountsService/LogIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MruVAccountsServiceServer).LogIn(ctx, req.(*LogInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MruVAccountsService_IsAccountExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAccountExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MruVAccountsServiceServer).IsAccountExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mruv.MruVAccountsService/IsAccountExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MruVAccountsServiceServer).IsAccountExists(ctx, req.(*IsAccountExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MruVAccountsService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MruVAccountsServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mruv.MruVAccountsService/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MruVAccountsServiceServer).GetAccount(ctx, req.(*AccountID))
	}
	return interceptor(ctx, in, info, handler)
}

func _MruVAccountsService_GetAccountCharacters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MruVAccountsServiceServer).GetAccountCharacters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mruv.MruVAccountsService/GetAccountCharacters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MruVAccountsServiceServer).GetAccountCharacters(ctx, req.(*AccountID))
	}
	return interceptor(ctx, in, info, handler)
}

var _MruVAccountsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mruv.MruVAccountsService",
	HandlerType: (*MruVAccountsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAccount",
			Handler:    _MruVAccountsService_RegisterAccount_Handler,
		},
		{
			MethodName: "LogIn",
			Handler:    _MruVAccountsService_LogIn_Handler,
		},
		{
			MethodName: "IsAccountExists",
			Handler:    _MruVAccountsService_IsAccountExists_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _MruVAccountsService_GetAccount_Handler,
		},
		{
			MethodName: "GetAccountCharacters",
			Handler:    _MruVAccountsService_GetAccountCharacters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts/accounts.proto",
}
