// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: accounts/accounts.proto

package accounts

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _accounts_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on AccountID with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *AccountID) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	return nil
}

// AccountIDValidationError is the validation error returned by
// AccountID.Validate if the designated constraints aren't met.
type AccountIDValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccountIDValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccountIDValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccountIDValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccountIDValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccountIDValidationError) ErrorName() string { return "AccountIDValidationError" }

// Error satisfies the builtin error interface
func (e AccountIDValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccountID.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccountIDValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccountIDValidationError{}

// Validate checks the field values on Account with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Account) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Login

	// no validation rules for Nick

	// no validation rules for Email

	return nil
}

// AccountValidationError is the validation error returned by Account.Validate
// if the designated constraints aren't met.
type AccountValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccountValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccountValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccountValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccountValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccountValidationError) ErrorName() string { return "AccountValidationError" }

// Error satisfies the builtin error interface
func (e AccountValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccount.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccountValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccountValidationError{}

// Validate checks the field values on RegisterAccountRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RegisterAccountRequest) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetAccount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegisterAccountRequestValidationError{
				field:  "Account",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Password

	return nil
}

// RegisterAccountRequestValidationError is the validation error returned by
// RegisterAccountRequest.Validate if the designated constraints aren't met.
type RegisterAccountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterAccountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterAccountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterAccountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterAccountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterAccountRequestValidationError) ErrorName() string {
	return "RegisterAccountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterAccountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterAccountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterAccountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterAccountRequestValidationError{}

// Validate checks the field values on RegisterAccountResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *RegisterAccountResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Success

	// no validation rules for AccountId

	return nil
}

// RegisterAccountResponseValidationError is the validation error returned by
// RegisterAccountResponse.Validate if the designated constraints aren't met.
type RegisterAccountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterAccountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterAccountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterAccountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterAccountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterAccountResponseValidationError) ErrorName() string {
	return "RegisterAccountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterAccountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterAccountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterAccountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterAccountResponseValidationError{}

// Validate checks the field values on LogInRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *LogInRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Login

	// no validation rules for Password

	return nil
}

// LogInRequestValidationError is the validation error returned by
// LogInRequest.Validate if the designated constraints aren't met.
type LogInRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogInRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogInRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogInRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogInRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogInRequestValidationError) ErrorName() string { return "LogInRequestValidationError" }

// Error satisfies the builtin error interface
func (e LogInRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogInRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogInRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogInRequestValidationError{}

// Validate checks the field values on LogInResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *LogInResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Success

	// no validation rules for AccountId

	return nil
}

// LogInResponseValidationError is the validation error returned by
// LogInResponse.Validate if the designated constraints aren't met.
type LogInResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogInResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogInResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogInResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogInResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogInResponseValidationError) ErrorName() string { return "LogInResponseValidationError" }

// Error satisfies the builtin error interface
func (e LogInResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogInResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogInResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogInResponseValidationError{}

// Validate checks the field values on GetAccountCharactersResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *GetAccountCharactersResponse) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetCharacters() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetAccountCharactersResponseValidationError{
					field:  fmt.Sprintf("Characters[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// GetAccountCharactersResponseValidationError is the validation error returned
// by GetAccountCharactersResponse.Validate if the designated constraints
// aren't met.
type GetAccountCharactersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAccountCharactersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAccountCharactersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAccountCharactersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAccountCharactersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAccountCharactersResponseValidationError) ErrorName() string {
	return "GetAccountCharactersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetAccountCharactersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAccountCharactersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAccountCharactersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAccountCharactersResponseValidationError{}
