// Code generated by protoc-gen-go. DO NOT EDIT.
// source: objects/objects.proto

package objects

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SA-MP Dynamic object data structure.
type Object struct {
	Model uint32  `protobuf:"varint,1,opt,name=model,proto3" json:"model,omitempty"`
	X     float32 `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y     float32 `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z     float32 `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	Rx    float32 `protobuf:"fixed32,5,opt,name=rx,proto3" json:"rx,omitempty"`
	Ry    float32 `protobuf:"fixed32,6,opt,name=ry,proto3" json:"ry,omitempty"`
	Rz    float32 `protobuf:"fixed32,7,opt,name=rz,proto3" json:"rz,omitempty"`
	// Virtual world id for which object will be visible. Set -1 to be visible for all.
	WorldId int32 `protobuf:"varint,8,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	// Interior id for which object will be visible. Set -1 to be visible for all.
	InteriorId int32 `protobuf:"varint,9,opt,name=interior_id,json=interiorId,proto3" json:"interior_id,omitempty"`
	// SA-MP player id for which object will be visible. Set -1 to be visible for all.
	PlayerId int32 `protobuf:"varint,10,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// Dynamic area id for which object will be visible. Set -1 to be visible for all.
	AreaId int32 `protobuf:"varint,11,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	// Default streamer setting is 300.0
	StreamDistance float32 `protobuf:"fixed32,12,opt,name=stream_distance,json=streamDistance,proto3" json:"stream_distance,omitempty"`
	// Default streamer setting is 0.0 = default game draw distance
	DrawDistance         float32  `protobuf:"fixed32,13,opt,name=draw_distance,json=drawDistance,proto3" json:"draw_distance,omitempty"`
	Priority             int32    `protobuf:"varint,15,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ad3a201d0ccaa04, []int{0}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetModel() uint32 {
	if m != nil {
		return m.Model
	}
	return 0
}

func (m *Object) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Object) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Object) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *Object) GetRx() float32 {
	if m != nil {
		return m.Rx
	}
	return 0
}

func (m *Object) GetRy() float32 {
	if m != nil {
		return m.Ry
	}
	return 0
}

func (m *Object) GetRz() float32 {
	if m != nil {
		return m.Rz
	}
	return 0
}

func (m *Object) GetWorldId() int32 {
	if m != nil {
		return m.WorldId
	}
	return 0
}

func (m *Object) GetInteriorId() int32 {
	if m != nil {
		return m.InteriorId
	}
	return 0
}

func (m *Object) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Object) GetAreaId() int32 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *Object) GetStreamDistance() float32 {
	if m != nil {
		return m.StreamDistance
	}
	return 0
}

func (m *Object) GetDrawDistance() float32 {
	if m != nil {
		return m.DrawDistance
	}
	return 0
}

func (m *Object) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

// Request message for rpc `CreateObject`.
type CreateObjectRequest struct {
	Object               *Object  `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateObjectRequest) Reset()         { *m = CreateObjectRequest{} }
func (m *CreateObjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateObjectRequest) ProtoMessage()    {}
func (*CreateObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ad3a201d0ccaa04, []int{1}
}

func (m *CreateObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateObjectRequest.Unmarshal(m, b)
}
func (m *CreateObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateObjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateObjectRequest.Merge(m, src)
}
func (m *CreateObjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateObjectRequest.Size(m)
}
func (m *CreateObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateObjectRequest proto.InternalMessageInfo

func (m *CreateObjectRequest) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

// Response message for rpc `CreateObject`.
type CreateObjectResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateObjectResponse) Reset()         { *m = CreateObjectResponse{} }
func (m *CreateObjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateObjectResponse) ProtoMessage()    {}
func (*CreateObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ad3a201d0ccaa04, []int{2}
}

func (m *CreateObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateObjectResponse.Unmarshal(m, b)
}
func (m *CreateObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateObjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateObjectResponse.Merge(m, src)
}
func (m *CreateObjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateObjectResponse.Size(m)
}
func (m *CreateObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateObjectResponse proto.InternalMessageInfo

func (m *CreateObjectResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Request message for rpc `GetObject`.
type GetObjectRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectRequest) Reset()         { *m = GetObjectRequest{} }
func (m *GetObjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectRequest) ProtoMessage()    {}
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ad3a201d0ccaa04, []int{3}
}

func (m *GetObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectRequest.Unmarshal(m, b)
}
func (m *GetObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectRequest.Marshal(b, m, deterministic)
}
func (m *GetObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectRequest.Merge(m, src)
}
func (m *GetObjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectRequest.Size(m)
}
func (m *GetObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectRequest proto.InternalMessageInfo

func (m *GetObjectRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Response message for rpc `GetObject`.
type GetObjectResponse struct {
	Object               *Object  `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectResponse) Reset()         { *m = GetObjectResponse{} }
func (m *GetObjectResponse) String() string { return proto.CompactTextString(m) }
func (*GetObjectResponse) ProtoMessage()    {}
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ad3a201d0ccaa04, []int{4}
}

func (m *GetObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectResponse.Unmarshal(m, b)
}
func (m *GetObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectResponse.Marshal(b, m, deterministic)
}
func (m *GetObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectResponse.Merge(m, src)
}
func (m *GetObjectResponse) XXX_Size() int {
	return xxx_messageInfo_GetObjectResponse.Size(m)
}
func (m *GetObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectResponse proto.InternalMessageInfo

func (m *GetObjectResponse) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

// Request message for rpc `UpdateObject`.
type UpdateObjectRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Object               *Object  `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateObjectRequest) Reset()         { *m = UpdateObjectRequest{} }
func (m *UpdateObjectRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateObjectRequest) ProtoMessage()    {}
func (*UpdateObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ad3a201d0ccaa04, []int{5}
}

func (m *UpdateObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateObjectRequest.Unmarshal(m, b)
}
func (m *UpdateObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateObjectRequest.Marshal(b, m, deterministic)
}
func (m *UpdateObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateObjectRequest.Merge(m, src)
}
func (m *UpdateObjectRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateObjectRequest.Size(m)
}
func (m *UpdateObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateObjectRequest proto.InternalMessageInfo

func (m *UpdateObjectRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateObjectRequest) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

// Response message for rpc `UpdateObject`.
type UpdateObjectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateObjectResponse) Reset()         { *m = UpdateObjectResponse{} }
func (m *UpdateObjectResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateObjectResponse) ProtoMessage()    {}
func (*UpdateObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ad3a201d0ccaa04, []int{6}
}

func (m *UpdateObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateObjectResponse.Unmarshal(m, b)
}
func (m *UpdateObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateObjectResponse.Marshal(b, m, deterministic)
}
func (m *UpdateObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateObjectResponse.Merge(m, src)
}
func (m *UpdateObjectResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateObjectResponse.Size(m)
}
func (m *UpdateObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateObjectResponse proto.InternalMessageInfo

// Request message for rpc `DeleteObject`.
type DeleteObjectRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteObjectRequest) Reset()         { *m = DeleteObjectRequest{} }
func (m *DeleteObjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteObjectRequest) ProtoMessage()    {}
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ad3a201d0ccaa04, []int{7}
}

func (m *DeleteObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteObjectRequest.Unmarshal(m, b)
}
func (m *DeleteObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteObjectRequest.Marshal(b, m, deterministic)
}
func (m *DeleteObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteObjectRequest.Merge(m, src)
}
func (m *DeleteObjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteObjectRequest.Size(m)
}
func (m *DeleteObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteObjectRequest proto.InternalMessageInfo

func (m *DeleteObjectRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Response message for rpc `DeleteObject`.
type DeleteObjectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteObjectResponse) Reset()         { *m = DeleteObjectResponse{} }
func (m *DeleteObjectResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteObjectResponse) ProtoMessage()    {}
func (*DeleteObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ad3a201d0ccaa04, []int{8}
}

func (m *DeleteObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteObjectResponse.Unmarshal(m, b)
}
func (m *DeleteObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteObjectResponse.Marshal(b, m, deterministic)
}
func (m *DeleteObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteObjectResponse.Merge(m, src)
}
func (m *DeleteObjectResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteObjectResponse.Size(m)
}
func (m *DeleteObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteObjectResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Object)(nil), "mruv.objects.Object")
	proto.RegisterType((*CreateObjectRequest)(nil), "mruv.objects.CreateObjectRequest")
	proto.RegisterType((*CreateObjectResponse)(nil), "mruv.objects.CreateObjectResponse")
	proto.RegisterType((*GetObjectRequest)(nil), "mruv.objects.GetObjectRequest")
	proto.RegisterType((*GetObjectResponse)(nil), "mruv.objects.GetObjectResponse")
	proto.RegisterType((*UpdateObjectRequest)(nil), "mruv.objects.UpdateObjectRequest")
	proto.RegisterType((*UpdateObjectResponse)(nil), "mruv.objects.UpdateObjectResponse")
	proto.RegisterType((*DeleteObjectRequest)(nil), "mruv.objects.DeleteObjectRequest")
	proto.RegisterType((*DeleteObjectResponse)(nil), "mruv.objects.DeleteObjectResponse")
}

func init() { proto.RegisterFile("objects/objects.proto", fileDescriptor_7ad3a201d0ccaa04) }

var fileDescriptor_7ad3a201d0ccaa04 = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x8e, 0xd2, 0x40,
	0x14, 0x4e, 0xbb, 0xf2, 0x77, 0x28, 0xcb, 0xee, 0x80, 0xee, 0x88, 0xc6, 0xc5, 0x9a, 0x75, 0x89,
	0x11, 0x1a, 0xf1, 0x09, 0x74, 0x37, 0x31, 0x5c, 0x18, 0x0d, 0x1b, 0xbd, 0xf0, 0x66, 0x53, 0x98,
	0x09, 0x8e, 0x81, 0x4e, 0x9d, 0x0e, 0x2c, 0xc5, 0x78, 0xe3, 0x2b, 0xf8, 0x52, 0xde, 0xeb, 0x23,
	0xf8, 0x20, 0x66, 0xa6, 0x03, 0xb4, 0x5d, 0xfc, 0xbb, 0x22, 0xdf, 0x39, 0xdf, 0x9c, 0xef, 0x9c,
	0xef, 0x0b, 0x85, 0x9b, 0x7c, 0xf4, 0x81, 0x8e, 0x65, 0xe4, 0x99, 0xdf, 0x5e, 0x28, 0xb8, 0xe4,
	0xc8, 0x99, 0x89, 0xf9, 0xa2, 0x67, 0x6a, 0xad, 0xbb, 0x13, 0xce, 0x27, 0x53, 0xea, 0xf9, 0x21,
	0xf3, 0xfc, 0x20, 0xe0, 0xd2, 0x97, 0x8c, 0x07, 0x86, 0xeb, 0xfe, 0xb0, 0xa1, 0xf8, 0x4a, 0x33,
	0x51, 0x13, 0x0a, 0x33, 0x4e, 0xe8, 0x14, 0x5b, 0x6d, 0xab, 0x53, 0x1b, 0x26, 0x00, 0x39, 0x60,
	0x2d, 0xb1, 0xdd, 0xb6, 0x3a, 0xf6, 0xd0, 0x5a, 0x2a, 0x14, 0xe3, 0xbd, 0x04, 0xc5, 0x0a, 0xad,
	0xf0, 0x8d, 0x04, 0xad, 0xd0, 0x3e, 0xd8, 0x62, 0x89, 0x0b, 0x1a, 0xda, 0x62, 0xa9, 0x71, 0x8c,
	0x8b, 0x06, 0xc7, 0x1a, 0xaf, 0x70, 0xc9, 0xe0, 0x15, 0xba, 0x0d, 0xe5, 0x2b, 0x2e, 0xa6, 0xe4,
	0x92, 0x11, 0x5c, 0x6e, 0x5b, 0x9d, 0xc2, 0xb0, 0xa4, 0xf1, 0x80, 0xa0, 0x63, 0xa8, 0xb2, 0x40,
	0x52, 0xc1, 0xb8, 0x50, 0xdd, 0x8a, 0xee, 0xc2, 0xba, 0x34, 0x20, 0xe8, 0x0e, 0x54, 0xc2, 0xa9,
	0x1f, 0x53, 0xdd, 0x06, 0xdd, 0x2e, 0x27, 0x85, 0x01, 0x41, 0x47, 0x50, 0xf2, 0x05, 0xf5, 0x55,
	0xab, 0xaa, 0x5b, 0x45, 0x05, 0x07, 0x04, 0x9d, 0x42, 0x3d, 0x92, 0x82, 0xfa, 0xb3, 0x4b, 0xc2,
	0x22, 0xe9, 0x07, 0x63, 0x8a, 0x1d, 0xbd, 0xce, 0x7e, 0x52, 0x3e, 0x37, 0x55, 0xf4, 0x00, 0x6a,
	0x44, 0xf8, 0x57, 0x5b, 0x5a, 0x4d, 0xd3, 0x1c, 0x55, 0xdc, 0x90, 0x5a, 0x50, 0x0e, 0xd5, 0x3a,
	0x4c, 0xc6, 0xb8, 0x6e, 0x56, 0x30, 0xd8, 0x3d, 0x83, 0xc6, 0x99, 0xa0, 0xbe, 0xa4, 0x89, 0xb7,
	0x43, 0xfa, 0x71, 0x4e, 0x23, 0x89, 0x1e, 0x43, 0x31, 0x89, 0x45, 0x7b, 0x5c, 0xed, 0x37, 0x7b,
	0xe9, 0xa8, 0x7a, 0x86, 0x6c, 0x38, 0xee, 0x43, 0x68, 0x66, 0x87, 0x44, 0x21, 0x0f, 0x22, 0xaa,
	0x8c, 0x64, 0xc4, 0xa4, 0x64, 0x33, 0xe2, 0xba, 0x70, 0xf0, 0x82, 0xca, 0xac, 0x52, 0x9e, 0xf3,
	0x0c, 0x0e, 0x53, 0x1c, 0x33, 0xe8, 0xff, 0xd6, 0xb9, 0x80, 0xc6, 0x9b, 0x90, 0x5c, 0xbb, 0x29,
	0xa7, 0x94, 0x1a, 0x6a, 0xff, 0xc3, 0xd0, 0x5b, 0xd0, 0xcc, 0x0e, 0x4d, 0x56, 0x73, 0x4f, 0xa0,
	0x71, 0x4e, 0xa7, 0xf4, 0x2f, 0x62, 0xea, 0x79, 0x96, 0x96, 0x3c, 0xef, 0x7f, 0xdb, 0x03, 0xf4,
	0x52, 0xcc, 0xdf, 0x26, 0xe5, 0xe8, 0x82, 0x8a, 0x05, 0x1b, 0x53, 0xc4, 0xc0, 0x49, 0x3b, 0x8a,
	0xee, 0x67, 0x77, 0xdb, 0x11, 0x59, 0xcb, 0xfd, 0x13, 0xc5, 0x2c, 0x8b, 0xbe, 0x7c, 0xff, 0xf9,
	0xd5, 0x76, 0x5c, 0xf0, 0x16, 0x4f, 0xcc, 0x7f, 0x11, 0x51, 0xa8, 0x6c, 0x0c, 0x47, 0xf7, 0xb2,
	0x43, 0xf2, 0x69, 0xb5, 0x8e, 0x7f, 0xdb, 0x37, 0x0a, 0x47, 0x5a, 0xe1, 0x10, 0xd5, 0xb7, 0x0a,
	0xde, 0x27, 0x46, 0x3e, 0x23, 0x0e, 0x4e, 0xda, 0xbf, 0xfc, 0x45, 0x3b, 0x02, 0xcb, 0x5f, 0xb4,
	0xd3, 0x7e, 0xac, 0xf5, 0x50, 0xff, 0x60, 0xab, 0x17, 0x6d, 0x04, 0xd3, 0x8e, 0xe7, 0x05, 0x77,
	0x84, 0x96, 0x17, 0xdc, 0x15, 0xd8, 0x5a, 0xf0, 0xd1, 0x35, 0xc1, 0xe7, 0xa7, 0xef, 0x4e, 0x26,
	0x4c, 0xbe, 0x9f, 0x8f, 0x7a, 0x63, 0x3e, 0xf3, 0x54, 0xa8, 0xdd, 0xe1, 0x6b, 0x4f, 0x4d, 0xec,
	0x86, 0xa3, 0xee, 0x84, 0xaf, 0xd9, 0xa3, 0xa2, 0xfe, 0xa2, 0x3d, 0xfd, 0x15, 0x00, 0x00, 0xff,
	0xff, 0xd3, 0x75, 0x90, 0xe9, 0x16, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MruVObjectsServiceClient is the client API for MruVObjectsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MruVObjectsServiceClient interface {
	// Create an object.
	CreateObject(ctx context.Context, in *CreateObjectRequest, opts ...grpc.CallOption) (*CreateObjectResponse, error)
	// Get an object.
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error)
	// Update an object.
	UpdateObject(ctx context.Context, in *UpdateObjectRequest, opts ...grpc.CallOption) (*UpdateObjectResponse, error)
	// Delete an object.
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error)
}

type mruVObjectsServiceClient struct {
	cc *grpc.ClientConn
}

func NewMruVObjectsServiceClient(cc *grpc.ClientConn) MruVObjectsServiceClient {
	return &mruVObjectsServiceClient{cc}
}

func (c *mruVObjectsServiceClient) CreateObject(ctx context.Context, in *CreateObjectRequest, opts ...grpc.CallOption) (*CreateObjectResponse, error) {
	out := new(CreateObjectResponse)
	err := c.cc.Invoke(ctx, "/mruv.objects.MruVObjectsService/CreateObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mruVObjectsServiceClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error) {
	out := new(GetObjectResponse)
	err := c.cc.Invoke(ctx, "/mruv.objects.MruVObjectsService/GetObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mruVObjectsServiceClient) UpdateObject(ctx context.Context, in *UpdateObjectRequest, opts ...grpc.CallOption) (*UpdateObjectResponse, error) {
	out := new(UpdateObjectResponse)
	err := c.cc.Invoke(ctx, "/mruv.objects.MruVObjectsService/UpdateObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mruVObjectsServiceClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error) {
	out := new(DeleteObjectResponse)
	err := c.cc.Invoke(ctx, "/mruv.objects.MruVObjectsService/DeleteObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MruVObjectsServiceServer is the server API for MruVObjectsService service.
type MruVObjectsServiceServer interface {
	// Create an object.
	CreateObject(context.Context, *CreateObjectRequest) (*CreateObjectResponse, error)
	// Get an object.
	GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error)
	// Update an object.
	UpdateObject(context.Context, *UpdateObjectRequest) (*UpdateObjectResponse, error)
	// Delete an object.
	DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error)
}

// UnimplementedMruVObjectsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMruVObjectsServiceServer struct {
}

func (*UnimplementedMruVObjectsServiceServer) CreateObject(ctx context.Context, req *CreateObjectRequest) (*CreateObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateObject not implemented")
}
func (*UnimplementedMruVObjectsServiceServer) GetObject(ctx context.Context, req *GetObjectRequest) (*GetObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetObject not implemented")
}
func (*UnimplementedMruVObjectsServiceServer) UpdateObject(ctx context.Context, req *UpdateObjectRequest) (*UpdateObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateObject not implemented")
}
func (*UnimplementedMruVObjectsServiceServer) DeleteObject(ctx context.Context, req *DeleteObjectRequest) (*DeleteObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteObject not implemented")
}

func RegisterMruVObjectsServiceServer(s *grpc.Server, srv MruVObjectsServiceServer) {
	s.RegisterService(&_MruVObjectsService_serviceDesc, srv)
}

func _MruVObjectsService_CreateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MruVObjectsServiceServer).CreateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mruv.objects.MruVObjectsService/CreateObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MruVObjectsServiceServer).CreateObject(ctx, req.(*CreateObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MruVObjectsService_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MruVObjectsServiceServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mruv.objects.MruVObjectsService/GetObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MruVObjectsServiceServer).GetObject(ctx, req.(*GetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MruVObjectsService_UpdateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MruVObjectsServiceServer).UpdateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mruv.objects.MruVObjectsService/UpdateObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MruVObjectsServiceServer).UpdateObject(ctx, req.(*UpdateObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MruVObjectsService_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MruVObjectsServiceServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mruv.objects.MruVObjectsService/DeleteObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MruVObjectsServiceServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MruVObjectsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mruv.objects.MruVObjectsService",
	HandlerType: (*MruVObjectsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateObject",
			Handler:    _MruVObjectsService_CreateObject_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _MruVObjectsService_GetObject_Handler,
		},
		{
			MethodName: "UpdateObject",
			Handler:    _MruVObjectsService_UpdateObject_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _MruVObjectsService_DeleteObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "objects/objects.proto",
}
