// Code generated by protoc-gen-go. DO NOT EDIT.
// source: characters/characters_model.proto

package characters

import (
	fmt "fmt"
	common "github.com/MruV-RP/mruv-pb-go/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeathType int32

const (
	DeathType_DEATH_TYPE_NONE    DeathType = 0
	DeathType_DEATH_TYPE_BW      DeathType = 1
	DeathType_DEATH_TYPE_BW_KILL DeathType = 2
	DeathType_DEATH_TYPE_CK      DeathType = 3
)

var DeathType_name = map[int32]string{
	0: "DEATH_TYPE_NONE",
	1: "DEATH_TYPE_BW",
	2: "DEATH_TYPE_BW_KILL",
	3: "DEATH_TYPE_CK",
}

var DeathType_value = map[string]int32{
	"DEATH_TYPE_NONE":    0,
	"DEATH_TYPE_BW":      1,
	"DEATH_TYPE_BW_KILL": 2,
	"DEATH_TYPE_CK":      3,
}

func (x DeathType) String() string {
	return proto.EnumName(DeathType_name, int32(x))
}

func (DeathType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd6cb9d47ecaab45, []int{0}
}

type Character struct {
	Id                   uint32           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId              uint32           `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	FirstName            string           `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName           string           `protobuf:"bytes,4,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	Age                  uint32           `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  uint32           `protobuf:"varint,6,opt,name=sex,proto3" json:"sex,omitempty"`
	Position             *common.Position `protobuf:"bytes,7,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Character) Reset()         { *m = Character{} }
func (m *Character) String() string { return proto.CompactTextString(m) }
func (*Character) ProtoMessage()    {}
func (*Character) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd6cb9d47ecaab45, []int{0}
}

func (m *Character) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Character.Unmarshal(m, b)
}
func (m *Character) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Character.Marshal(b, m, deterministic)
}
func (m *Character) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Character.Merge(m, src)
}
func (m *Character) XXX_Size() int {
	return xxx_messageInfo_Character.Size(m)
}
func (m *Character) XXX_DiscardUnknown() {
	xxx_messageInfo_Character.DiscardUnknown(m)
}

var xxx_messageInfo_Character proto.InternalMessageInfo

func (m *Character) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Character) GetOwnerId() uint32 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *Character) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Character) GetSecondName() string {
	if m != nil {
		return m.SecondName
	}
	return ""
}

func (m *Character) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Character) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *Character) GetPosition() *common.Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type CharacterID struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CharacterID) Reset()         { *m = CharacterID{} }
func (m *CharacterID) String() string { return proto.CompactTextString(m) }
func (*CharacterID) ProtoMessage()    {}
func (*CharacterID) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd6cb9d47ecaab45, []int{1}
}

func (m *CharacterID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharacterID.Unmarshal(m, b)
}
func (m *CharacterID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharacterID.Marshal(b, m, deterministic)
}
func (m *CharacterID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharacterID.Merge(m, src)
}
func (m *CharacterID) XXX_Size() int {
	return xxx_messageInfo_CharacterID.Size(m)
}
func (m *CharacterID) XXX_DiscardUnknown() {
	xxx_messageInfo_CharacterID.DiscardUnknown(m)
}

var xxx_messageInfo_CharacterID proto.InternalMessageInfo

func (m *CharacterID) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("mruv.DeathType", DeathType_name, DeathType_value)
	proto.RegisterType((*Character)(nil), "mruv.Character")
	proto.RegisterType((*CharacterID)(nil), "mruv.CharacterID")
}

func init() { proto.RegisterFile("characters/characters_model.proto", fileDescriptor_bd6cb9d47ecaab45) }

var fileDescriptor_bd6cb9d47ecaab45 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xdd, 0x4e, 0xc2, 0x30,
	0x18, 0x86, 0xdd, 0x40, 0x60, 0x1f, 0x01, 0x67, 0x35, 0x66, 0x9a, 0x10, 0x91, 0xa3, 0x85, 0x84,
	0x2d, 0xd1, 0x2b, 0x90, 0x9f, 0x44, 0x02, 0x22, 0x59, 0x88, 0x46, 0x0f, 0x5c, 0xca, 0x56, 0xa1,
	0x89, 0x5d, 0x97, 0xb6, 0x28, 0xde, 0xa0, 0xd7, 0x65, 0xd6, 0x21, 0x22, 0x67, 0x5f, 0x9f, 0xe7,
	0x6d, 0xd3, 0xb7, 0x85, 0xab, 0x68, 0x89, 0x05, 0x8e, 0x14, 0x11, 0xd2, 0xff, 0x1b, 0x43, 0xc6,
	0x63, 0xf2, 0xee, 0xa5, 0x82, 0x2b, 0x8e, 0x8a, 0x4c, 0xac, 0x3e, 0x2e, 0x4e, 0x23, 0xce, 0x18,
	0x4f, 0x7c, 0x99, 0x62, 0x45, 0xf1, 0xc6, 0xb5, 0xbe, 0x0d, 0xb0, 0x7a, 0xbf, 0xdb, 0x50, 0x1d,
	0x4c, 0x1a, 0x3b, 0x46, 0xd3, 0x70, 0x6b, 0x81, 0x49, 0x63, 0x74, 0x0e, 0x15, 0xfe, 0x99, 0x10,
	0x11, 0xd2, 0xd8, 0x31, 0x35, 0x2d, 0xeb, 0xf5, 0x30, 0x46, 0x0d, 0x80, 0x37, 0x2a, 0xa4, 0x0a,
	0x13, 0xcc, 0x88, 0x53, 0x68, 0x1a, 0xae, 0x15, 0x58, 0x9a, 0x4c, 0x30, 0x23, 0xe8, 0x12, 0xaa,
	0x92, 0x44, 0x3c, 0x89, 0x73, 0x5f, 0xd4, 0x1e, 0x72, 0xa4, 0x03, 0x36, 0x14, 0xf0, 0x82, 0x38,
	0x87, 0xfa, 0xd4, 0x6c, 0xcc, 0x88, 0x24, 0x6b, 0xa7, 0x94, 0x13, 0x49, 0xd6, 0xa8, 0x0d, 0x95,
	0x94, 0x4b, 0xaa, 0x28, 0x4f, 0x9c, 0x72, 0xd3, 0x70, 0xab, 0xd7, 0x75, 0x2f, 0xeb, 0xe2, 0x4d,
	0x37, 0x34, 0xd8, 0xfa, 0x56, 0x03, 0xaa, 0xdb, 0x1e, 0xc3, 0xfe, 0x7e, 0x93, 0xf6, 0x2b, 0x58,
	0x7d, 0x82, 0xd5, 0x72, 0xf6, 0x95, 0x12, 0x74, 0x02, 0x47, 0xfd, 0xc1, 0xed, 0xec, 0x2e, 0x9c,
	0x3d, 0x4f, 0x07, 0xe1, 0xe4, 0x61, 0x32, 0xb0, 0x0f, 0xd0, 0x31, 0xd4, 0x76, 0x60, 0xf7, 0xc9,
	0x36, 0xd0, 0x19, 0xa0, 0x7f, 0x28, 0x1c, 0x0d, 0xc7, 0x63, 0xdb, 0xdc, 0x8b, 0xf6, 0x46, 0x76,
	0xa1, 0xdb, 0x7e, 0x71, 0x17, 0x54, 0x2d, 0x57, 0x73, 0x2f, 0xe2, 0xcc, 0xbf, 0x17, 0xab, 0xc7,
	0x4e, 0x30, 0xf5, 0xb3, 0xcb, 0x76, 0xd2, 0x79, 0x67, 0xc1, 0x77, 0xfe, 0x66, 0x5e, 0xd2, 0x4f,
	0x7f, 0xf3, 0x13, 0x00, 0x00, 0xff, 0xff, 0x68, 0x09, 0xb4, 0x3b, 0xbb, 0x01, 0x00, 0x00,
}
