// Code generated by protoc-gen-go. DO NOT EDIT.
// source: houses/houses.proto

package houses

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message for rpc `CreateHouse`.
type CreateHouseRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHouseRequest) Reset()         { *m = CreateHouseRequest{} }
func (m *CreateHouseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHouseRequest) ProtoMessage()    {}
func (*CreateHouseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c320ad1a4289b196, []int{0}
}

func (m *CreateHouseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHouseRequest.Unmarshal(m, b)
}
func (m *CreateHouseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHouseRequest.Marshal(b, m, deterministic)
}
func (m *CreateHouseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHouseRequest.Merge(m, src)
}
func (m *CreateHouseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHouseRequest.Size(m)
}
func (m *CreateHouseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHouseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHouseRequest proto.InternalMessageInfo

// Response message for rpc `CreateHouse`.
type CreateHouseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHouseResponse) Reset()         { *m = CreateHouseResponse{} }
func (m *CreateHouseResponse) String() string { return proto.CompactTextString(m) }
func (*CreateHouseResponse) ProtoMessage()    {}
func (*CreateHouseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c320ad1a4289b196, []int{1}
}

func (m *CreateHouseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHouseResponse.Unmarshal(m, b)
}
func (m *CreateHouseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHouseResponse.Marshal(b, m, deterministic)
}
func (m *CreateHouseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHouseResponse.Merge(m, src)
}
func (m *CreateHouseResponse) XXX_Size() int {
	return xxx_messageInfo_CreateHouseResponse.Size(m)
}
func (m *CreateHouseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHouseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHouseResponse proto.InternalMessageInfo

// Request message for rpc `GetHouse`.
type GetHouseRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHouseRequest) Reset()         { *m = GetHouseRequest{} }
func (m *GetHouseRequest) String() string { return proto.CompactTextString(m) }
func (*GetHouseRequest) ProtoMessage()    {}
func (*GetHouseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c320ad1a4289b196, []int{2}
}

func (m *GetHouseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHouseRequest.Unmarshal(m, b)
}
func (m *GetHouseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHouseRequest.Marshal(b, m, deterministic)
}
func (m *GetHouseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHouseRequest.Merge(m, src)
}
func (m *GetHouseRequest) XXX_Size() int {
	return xxx_messageInfo_GetHouseRequest.Size(m)
}
func (m *GetHouseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHouseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHouseRequest proto.InternalMessageInfo

func (m *GetHouseRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Response message for rpc `GetHouse`.
type GetHouseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHouseResponse) Reset()         { *m = GetHouseResponse{} }
func (m *GetHouseResponse) String() string { return proto.CompactTextString(m) }
func (*GetHouseResponse) ProtoMessage()    {}
func (*GetHouseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c320ad1a4289b196, []int{3}
}

func (m *GetHouseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHouseResponse.Unmarshal(m, b)
}
func (m *GetHouseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHouseResponse.Marshal(b, m, deterministic)
}
func (m *GetHouseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHouseResponse.Merge(m, src)
}
func (m *GetHouseResponse) XXX_Size() int {
	return xxx_messageInfo_GetHouseResponse.Size(m)
}
func (m *GetHouseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHouseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHouseResponse proto.InternalMessageInfo

// Request message for rpc `UpdateHouse`.
type UpdateHouseRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateHouseRequest) Reset()         { *m = UpdateHouseRequest{} }
func (m *UpdateHouseRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateHouseRequest) ProtoMessage()    {}
func (*UpdateHouseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c320ad1a4289b196, []int{4}
}

func (m *UpdateHouseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHouseRequest.Unmarshal(m, b)
}
func (m *UpdateHouseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHouseRequest.Marshal(b, m, deterministic)
}
func (m *UpdateHouseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHouseRequest.Merge(m, src)
}
func (m *UpdateHouseRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateHouseRequest.Size(m)
}
func (m *UpdateHouseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHouseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHouseRequest proto.InternalMessageInfo

func (m *UpdateHouseRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Response message for rpc `UpdateHouse`.
type UpdateHouseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateHouseResponse) Reset()         { *m = UpdateHouseResponse{} }
func (m *UpdateHouseResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateHouseResponse) ProtoMessage()    {}
func (*UpdateHouseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c320ad1a4289b196, []int{5}
}

func (m *UpdateHouseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHouseResponse.Unmarshal(m, b)
}
func (m *UpdateHouseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHouseResponse.Marshal(b, m, deterministic)
}
func (m *UpdateHouseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHouseResponse.Merge(m, src)
}
func (m *UpdateHouseResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateHouseResponse.Size(m)
}
func (m *UpdateHouseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHouseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHouseResponse proto.InternalMessageInfo

// Request message for rpc `DeleteHouse`.
type DeleteHouseRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHouseRequest) Reset()         { *m = DeleteHouseRequest{} }
func (m *DeleteHouseRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteHouseRequest) ProtoMessage()    {}
func (*DeleteHouseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c320ad1a4289b196, []int{6}
}

func (m *DeleteHouseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHouseRequest.Unmarshal(m, b)
}
func (m *DeleteHouseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHouseRequest.Marshal(b, m, deterministic)
}
func (m *DeleteHouseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHouseRequest.Merge(m, src)
}
func (m *DeleteHouseRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteHouseRequest.Size(m)
}
func (m *DeleteHouseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHouseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHouseRequest proto.InternalMessageInfo

func (m *DeleteHouseRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Response message for rpc `DeleteHouse`.
type DeleteHouseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHouseResponse) Reset()         { *m = DeleteHouseResponse{} }
func (m *DeleteHouseResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteHouseResponse) ProtoMessage()    {}
func (*DeleteHouseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c320ad1a4289b196, []int{7}
}

func (m *DeleteHouseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHouseResponse.Unmarshal(m, b)
}
func (m *DeleteHouseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHouseResponse.Marshal(b, m, deterministic)
}
func (m *DeleteHouseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHouseResponse.Merge(m, src)
}
func (m *DeleteHouseResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteHouseResponse.Size(m)
}
func (m *DeleteHouseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHouseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHouseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateHouseRequest)(nil), "mruv.houses.CreateHouseRequest")
	proto.RegisterType((*CreateHouseResponse)(nil), "mruv.houses.CreateHouseResponse")
	proto.RegisterType((*GetHouseRequest)(nil), "mruv.houses.GetHouseRequest")
	proto.RegisterType((*GetHouseResponse)(nil), "mruv.houses.GetHouseResponse")
	proto.RegisterType((*UpdateHouseRequest)(nil), "mruv.houses.UpdateHouseRequest")
	proto.RegisterType((*UpdateHouseResponse)(nil), "mruv.houses.UpdateHouseResponse")
	proto.RegisterType((*DeleteHouseRequest)(nil), "mruv.houses.DeleteHouseRequest")
	proto.RegisterType((*DeleteHouseResponse)(nil), "mruv.houses.DeleteHouseResponse")
}

func init() { proto.RegisterFile("houses/houses.proto", fileDescriptor_c320ad1a4289b196) }

var fileDescriptor_c320ad1a4289b196 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4d, 0x4a, 0xc3, 0x40,
	0x14, 0xc7, 0x69, 0x05, 0x91, 0x57, 0xb5, 0xf6, 0xd5, 0xa2, 0x94, 0x8a, 0x35, 0x14, 0x11, 0xa1,
	0x19, 0xac, 0x37, 0x50, 0x41, 0x37, 0x82, 0x54, 0x74, 0xe1, 0xca, 0xb4, 0x79, 0xa4, 0x03, 0x6d,
	0x26, 0x66, 0x26, 0xdd, 0x88, 0x1b, 0xaf, 0xe0, 0x49, 0x3c, 0x8b, 0x57, 0xf0, 0x20, 0x92, 0x64,
	0x4a, 0x92, 0x49, 0x8a, 0xab, 0xc0, 0xcb, 0xff, 0x23, 0xef, 0xf7, 0x02, 0xed, 0x99, 0x88, 0x24,
	0x49, 0x96, 0x3e, 0xec, 0x20, 0x14, 0x4a, 0x60, 0x63, 0x11, 0x46, 0x4b, 0x3b, 0x1d, 0x75, 0x7b,
	0x9e, 0x10, 0xde, 0x9c, 0x98, 0x13, 0x70, 0xe6, 0xf8, 0xbe, 0x50, 0x8e, 0xe2, 0xc2, 0xd7, 0x52,
	0x6b, 0x1f, 0xf0, 0x3a, 0x24, 0x47, 0xd1, 0x5d, 0xac, 0x1e, 0xd3, 0x5b, 0x44, 0x52, 0x59, 0x1d,
	0x68, 0x17, 0xa6, 0x32, 0x10, 0xbe, 0x24, 0xeb, 0x04, 0x9a, 0xb7, 0xa4, 0xf2, 0x4a, 0xdc, 0x85,
	0x3a, 0x77, 0x0f, 0x6b, 0xfd, 0xda, 0xd9, 0xce, 0xb8, 0xce, 0x5d, 0x0b, 0x61, 0x2f, 0x93, 0x68,
	0xdb, 0x00, 0xf0, 0x29, 0x70, 0x8d, 0x8e, 0x92, 0xb3, 0x03, 0xed, 0x82, 0x2a, 0x33, 0xdf, 0xd0,
	0x9c, 0xfe, 0x37, 0x17, 0x54, 0xa9, 0x79, 0xf4, 0xbd, 0x01, 0xad, 0xfb, 0x30, 0x7a, 0x4e, 0xa6,
	0xf2, 0x91, 0xc2, 0x25, 0x9f, 0x12, 0xba, 0xd0, 0xc8, 0x6d, 0x87, 0xc7, 0x76, 0x0e, 0x97, 0x5d,
	0xa6, 0xd1, 0xed, 0xaf, 0x17, 0xe8, 0x8f, 0xc4, 0xcf, 0x9f, 0xdf, 0xaf, 0xfa, 0xb6, 0x05, 0x6c,
	0x79, 0xa1, 0x4f, 0x81, 0xaf, 0xb0, 0xb5, 0x22, 0x81, 0xbd, 0x42, 0x82, 0xc1, 0xb0, 0x7b, 0xb4,
	0xe6, 0xad, 0x0e, 0x3f, 0x48, 0xc2, 0x5b, 0xd8, 0xcc, 0xc2, 0xd9, 0x3b, 0x77, 0x3f, 0x90, 0x43,
	0x23, 0x47, 0xcc, 0xd8, 0xa3, 0x4c, 0xdc, 0xd8, 0xa3, 0x0a, 0xb6, 0xae, 0x1a, 0x55, 0x55, 0xe5,
	0xf8, 0x1a, 0x55, 0xe5, 0xfb, 0x18, 0x55, 0x15, 0xa7, 0x59, 0x55, 0x9d, 0x9b, 0x55, 0x57, 0xa7,
	0x2f, 0x03, 0x8f, 0xab, 0x59, 0x34, 0xb1, 0xa7, 0x62, 0xc1, 0xe2, 0xeb, 0x0d, 0xc7, 0x0f, 0x2c,
	0x8e, 0x1b, 0x06, 0x93, 0xa1, 0x27, 0xb4, 0x78, 0xb2, 0x99, 0xfc, 0xc0, 0x97, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xff, 0x88, 0x93, 0xe6, 0x02, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MruVHousesServiceClient is the client API for MruVHousesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MruVHousesServiceClient interface {
	// Create a house.
	CreateHouse(ctx context.Context, in *CreateHouseRequest, opts ...grpc.CallOption) (*CreateHouseResponse, error)
	// Get a house.
	GetHouse(ctx context.Context, in *GetHouseRequest, opts ...grpc.CallOption) (*GetHouseResponse, error)
	// Update a house.
	UpdateHouse(ctx context.Context, in *UpdateHouseRequest, opts ...grpc.CallOption) (*UpdateHouseResponse, error)
	// Delete a house.
	DeleteHouse(ctx context.Context, in *DeleteHouseRequest, opts ...grpc.CallOption) (*DeleteHouseResponse, error)
}

type mruVHousesServiceClient struct {
	cc *grpc.ClientConn
}

func NewMruVHousesServiceClient(cc *grpc.ClientConn) MruVHousesServiceClient {
	return &mruVHousesServiceClient{cc}
}

func (c *mruVHousesServiceClient) CreateHouse(ctx context.Context, in *CreateHouseRequest, opts ...grpc.CallOption) (*CreateHouseResponse, error) {
	out := new(CreateHouseResponse)
	err := c.cc.Invoke(ctx, "/mruv.houses.MruVHousesService/CreateHouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mruVHousesServiceClient) GetHouse(ctx context.Context, in *GetHouseRequest, opts ...grpc.CallOption) (*GetHouseResponse, error) {
	out := new(GetHouseResponse)
	err := c.cc.Invoke(ctx, "/mruv.houses.MruVHousesService/GetHouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mruVHousesServiceClient) UpdateHouse(ctx context.Context, in *UpdateHouseRequest, opts ...grpc.CallOption) (*UpdateHouseResponse, error) {
	out := new(UpdateHouseResponse)
	err := c.cc.Invoke(ctx, "/mruv.houses.MruVHousesService/UpdateHouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mruVHousesServiceClient) DeleteHouse(ctx context.Context, in *DeleteHouseRequest, opts ...grpc.CallOption) (*DeleteHouseResponse, error) {
	out := new(DeleteHouseResponse)
	err := c.cc.Invoke(ctx, "/mruv.houses.MruVHousesService/DeleteHouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MruVHousesServiceServer is the server API for MruVHousesService service.
type MruVHousesServiceServer interface {
	// Create a house.
	CreateHouse(context.Context, *CreateHouseRequest) (*CreateHouseResponse, error)
	// Get a house.
	GetHouse(context.Context, *GetHouseRequest) (*GetHouseResponse, error)
	// Update a house.
	UpdateHouse(context.Context, *UpdateHouseRequest) (*UpdateHouseResponse, error)
	// Delete a house.
	DeleteHouse(context.Context, *DeleteHouseRequest) (*DeleteHouseResponse, error)
}

// UnimplementedMruVHousesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMruVHousesServiceServer struct {
}

func (*UnimplementedMruVHousesServiceServer) CreateHouse(ctx context.Context, req *CreateHouseRequest) (*CreateHouseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHouse not implemented")
}
func (*UnimplementedMruVHousesServiceServer) GetHouse(ctx context.Context, req *GetHouseRequest) (*GetHouseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHouse not implemented")
}
func (*UnimplementedMruVHousesServiceServer) UpdateHouse(ctx context.Context, req *UpdateHouseRequest) (*UpdateHouseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHouse not implemented")
}
func (*UnimplementedMruVHousesServiceServer) DeleteHouse(ctx context.Context, req *DeleteHouseRequest) (*DeleteHouseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHouse not implemented")
}

func RegisterMruVHousesServiceServer(s *grpc.Server, srv MruVHousesServiceServer) {
	s.RegisterService(&_MruVHousesService_serviceDesc, srv)
}

func _MruVHousesService_CreateHouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MruVHousesServiceServer).CreateHouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mruv.houses.MruVHousesService/CreateHouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MruVHousesServiceServer).CreateHouse(ctx, req.(*CreateHouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MruVHousesService_GetHouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MruVHousesServiceServer).GetHouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mruv.houses.MruVHousesService/GetHouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MruVHousesServiceServer).GetHouse(ctx, req.(*GetHouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MruVHousesService_UpdateHouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MruVHousesServiceServer).UpdateHouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mruv.houses.MruVHousesService/UpdateHouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MruVHousesServiceServer).UpdateHouse(ctx, req.(*UpdateHouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MruVHousesService_DeleteHouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MruVHousesServiceServer).DeleteHouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mruv.houses.MruVHousesService/DeleteHouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MruVHousesServiceServer).DeleteHouse(ctx, req.(*DeleteHouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MruVHousesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mruv.houses.MruVHousesService",
	HandlerType: (*MruVHousesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHouse",
			Handler:    _MruVHousesService_CreateHouse_Handler,
		},
		{
			MethodName: "GetHouse",
			Handler:    _MruVHousesService_GetHouse_Handler,
		},
		{
			MethodName: "UpdateHouse",
			Handler:    _MruVHousesService_UpdateHouse_Handler,
		},
		{
			MethodName: "DeleteHouse",
			Handler:    _MruVHousesService_DeleteHouse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "houses/houses.proto",
}
